---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: {{ printf "%s-postgres" (include "shop-learn.fullname" . ) }}
  # Sealed for namespace shop-learn (strict scope) - chart installs there
  namespace: shop-learn
  labels:
    {{- include "shop-learn.labels" . | nindent 4 }}
spec:
  encryptedData:
    DATABASE_URL: AgAzwYSTLYbeq2uQX65wJZ6HOPj9SevClXVKMYkaBiRrvfHTtFCVpQ43eKJApGaZOV7gHOa9Zy/9TQn043KSjgmi1DtNJ8EbvvL+uDS7QC5fsXeYer7r28jav/4VZGEWLaw+cXQtFSxG7VmHvUL6RLPusvXjYc7Vcpb3r60wF1UT/6OxvfNYZkgdplQoZ2D9CACVSNalvD+ZXLrXR4xY2m3x8dEL+hjooIFSHlk8bnMCs6C7yhynp10Hbwo6RHMP/B9/8YPPVXXARh/+aHsh53g+LaTkymOsbsRzt0jEJylclGFA5aylYvms+GxtssjIcykEcmTVlBQwjw9E6oAu9i1PbJ1ZnihL6dauHvE5Zz1WM4taaCClG+aDlYFWLZeAfIuR8J6X6cuXlMDVAXCPzjlKs3KHB+8rflHgBEzjkVD+N3JozCIJWE8fmgSwJUCvS9q60y9zrXuRf+gcqQ/kF4K34IdhhiV5ioOc+ofwBuwp9Kk7oAaowkEQc5zgJxtmjf/dh2HeeLsJBXWNPjPUBi/g49t5qWJglEOzhC8vDHtFoWDETi/PXM64YuRernQVXGKG1s+lCXiUKxf/P2cEtQV2Mxtet1lS5AnfXFdGcEoBMTK9nSV0LLY+3yDwhJ5l5yXJnfDTcH4u8nH4ZF06pnpGD+ZbCfF5GlvYrBoofLwXr8p+PbDoXb3kDMUMHVKk+XQ2yte9TvXYQyiFVDJJlUmPMMEW3p4ClXwgY33+SIYQaj3WYYr6yIsdsSA1cOjOj3a3sJZgIzS+7tnpoZjv6APVyzlV/uTvVq9dkOI=
    POSTGRES_PASSWORD: AgBC9O4L7ZisXf4lCiL6KOyo7iasO0ZTQSX8IvwHXq9LfiYOMzjzAEkEVwmAxW+D/0bF/tjWDxkhau8CQtKR07Rl95EWj7ghAIimHbNWN3oX/kUG2DWk3/jqpZ2roLCSfzIcICayfpvQYlTzVSUbaeRjsuIHvtNQ0/VyE1oqe7Xc2dtRlZoVe9RgzqDuXofBwM39UIlP/tRaJB/V9TfagZTxZIr9neX0CNtcLPR66THLBBnpLyJFTRWSDeX4B3BE2g6X0l5F6zFTybTpCNiVzQDpTXWOBx9eiXqNHAaQKR4FIGYd8BIvd8bQR9eaPHPhqpzwQZLOeXgrNys5UUQGjKVPZspnWBLYRRaAUHcqrfhUPsog6dgiF+5nbywNjDodw5npGTLO7W71F1c8g7ktUfyFznNLqGZSyhwRSyFjwa9GpGc7KgzO20pjDD/DqdbODBho/xXZtAMQS8F/YGWVhmcJAVJnj+3z0jSO2MnZN2yfYqIyH64XSA5vAtIL3ndNUyW68QaWEmlnu7IekrQdIMzF5es5sfMG9b31ZCCtI4k8onjXzzyPv7Y+KG7zSQJYe8Ed9GFtJG/xxRhFcNVK6B752cTOAbW9JlrTWw8YblqGDjw5zPum8ipD+VTDq4q5g8Frr9aWMIGAqG+XEL0buDfh849llIdhtYXRjnqnlX2ZI/RiCFN/LgCk46BdDDnJ82+nKKrAtSoENHkMn9zqiLhQIJkLbpgTPITmsYP+ira2qQ==
  template:
    metadata:
      name: shop-learn-postgres
      namespace: shop-learn
