name: ci
on: [push, pull_request]
jobs:
  test-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: node --test services/api-gateway/test/*.test.js
      - run: node --test services/products/test/*.test.js
      - run: node --test services/orders/test/*.test.js
      - run: node --test services/notifications/test/*.test.js
      - run: docker build ./services/api-gateway
      - run: docker build ./services/products
      - run: docker build ./services/orders
      - run: docker build ./services/notifications
